In [ ]:
import numpy as np;

In [6]:
import numpy as np;

array = np.array([1,2,3,4,5,6,7,8,9])
print(array)
print(type(array))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np;

array_1 = np.array([1,2,3,4,5])
array_2 = np.array([6,7,8,9,10])

sum_of_array = array_1 + array_2
print(sum_of_array)

difference_of_array = array_1 - array_2
print(difference_of_array)

mult_of_array = array_1 * array_2
print(mult_of_array)

dev_of_array = array_1/ array_2
print(dev_of_array)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
array = np.array([1,2,3,4,5,6])

#Prints sum of the array
summaration = np.sum(array)
print(summaration)

#Prints average
average = np.mean(array)
print(average)

#Print max of the array
print(np.max(array))

#Print min of the array
print(np.min(array))

#Print sqrt of the array each elements0
print(np.sqrt(array))

21
3.5
6
1
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [16]:
import numpy as np;

arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
2


In [18]:
import numpy as np;

array = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]],
    [[13, 14], [15, 16], [17, 18]]
])

print(array)
print(array.shape)
print(array.size)
print(array.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
(3, 3, 2)
18
3


In [22]:
import numpy as np

arr = np.array([
    [
        [1,2],
        [9,10]
    ],
    [
        [3,4],
        [11,12]
    ],
    [
        [5,6],
        [13,14]
    ],
    [
        [7,8],
        [15,16]
    ]
])

print(arr.shape)   # (4, 2, 2)


(4, 2, 2)


In [23]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print(arr[1,2])

6


In [ ]:
import numpy as np;

arr = np.array([
    [[1,2] ,[5,7] ,[9,8]],
    [[3,4] , [6,8] ,[10,12]],
    [[11,13] , [14,16] , [18,20]]
])

print(arr[1,0,0])
print(arr[-2,-3,-2])

print(arr[2,1,0])
print(arr[-1,-2,-2])

print(arr[0,0,1])
print(arr[-3,-3,-1])

3
3
14
14
2
2


In [5]:
import numpy as np;

arr= np.array([10,45,74,14,13,67,70,70,4,75,8])
condition = arr > 15
print(condition)

filtered_arr = arr[condition]
print(filtered_arr)

[False  True  True False False  True  True  True False  True False]
[45 74 67 70 70 75]


In [ ]:
import numpy as np;

arr= np.array([10,45,74,14,13,67,70,70,4,75,8])
filtered_arr = arr[arr > 15]
print(filtered_arr)

[10 14 13  4  8]


In [7]:
import numpy as np;

arr = np.array([
    [12,5,7,20],
    [3,15,8,2],
    [10,25,6,18],
    [4,11,30,9]
])

filtered_arr = arr[((arr> 10) | (arr<5)) & (arr != 15)]
print(filtered_arr)

[12 20  3  2 25 18  4 11 30]


In [10]:
import numpy as np;

array = np.zeros((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as np;

array = np.full((2,3) , 5)
print(array)

[[5 5 5]
 [5 5 5]]


In [13]:
import numpy as np;

array = np.empty((2,3))
print(array)

[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]
