In [ ]:
import numpy as np;

In [6]:
import numpy as np;

array = np.array([1,2,3,4,5,6,7,8,9])
print(array)
print(type(array))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np;

array_1 = np.array([1,2,3,4,5])
array_2 = np.array([6,7,8,9,10])

sum_of_array = array_1 + array_2
print(sum_of_array)

difference_of_array = array_1 - array_2
print(difference_of_array)

mult_of_array = array_1 * array_2
print(mult_of_array)

dev_of_array = array_1/ array_2
print(dev_of_array)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
array = np.array([1,2,3,4,5,6])

#Prints sum of the array
summaration = np.sum(array)
print(summaration)

#Prints average
average = np.mean(array)
print(average)

#Print max of the array
print(np.max(array))

#Print min of the array
print(np.min(array))

#Print sqrt of the array each elements0
print(np.sqrt(array))

21
3.5
6
1
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [16]:
import numpy as np;

arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
2


In [18]:
import numpy as np;

array = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]],
    [[13, 14], [15, 16], [17, 18]]
])

print(array)
print(array.shape)
print(array.size)
print(array.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
(3, 3, 2)
18
3


In [22]:
import numpy as np

arr = np.array([
    [
        [1,2],
        [9,10]
    ],
    [
        [3,4],
        [11,12]
    ],
    [
        [5,6],
        [13,14]
    ],
    [
        [7,8],
        [15,16]
    ]
])

print(arr.shape)   # (4, 2, 2)


(4, 2, 2)


In [23]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print(arr[1,2])

6


In [ ]:
import numpy as np;

arr = np.array([
    [[1,2] ,[5,7] ,[9,8]],
    [[3,4] , [6,8] ,[10,12]],
    [[11,13] , [14,16] , [18,20]]
])

print(arr[1,0,0])
print(arr[-2,-3,-2])

print(arr[2,1,0])
print(arr[-1,-2,-2])

print(arr[0,0,1])
print(arr[-3,-3,-1])

3
3
14
14
2
2


In [5]:
import numpy as np;

arr= np.array([10,45,74,14,13,67,70,70,4,75,8])
condition = arr > 15
print(condition)

filtered_arr = arr[condition]
print(filtered_arr)

[False  True  True False False  True  True  True False  True False]
[45 74 67 70 70 75]


In [ ]:
import numpy as np;

arr= np.array([10,45,74,14,13,67,70,70,4,75,8])
filtered_arr = arr[arr > 15]
print(filtered_arr)

[10 14 13  4  8]


In [7]:
import numpy as np;

arr = np.array([
    [12,5,7,20],
    [3,15,8,2],
    [10,25,6,18],
    [4,11,30,9]
])

filtered_arr = arr[((arr> 10) | (arr<5)) & (arr != 15)]
print(filtered_arr)

[12 20  3  2 25 18  4 11 30]


In [10]:
import numpy as np;

array = np.zeros((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as np;

array = np.full((2,3) , 5)
print(array)

[[5 5 5]
 [5 5 5]]


In [13]:
import numpy as np;

array = np.empty((2,3))
print(array)

[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]


In [15]:
import pandas as pd

In [17]:
import pandas as pd

data = {
    "Name" : ["Ann" , "John" , "David" , "Serina"],
    "Age" : [21,23,56,23]
}

df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age
0     Ann   21
1    John   23
2   David   56
3  Serina   23
<class 'pandas.core.frame.DataFrame'>


In [24]:
import pandas as pd

data = {
    "Name" : ["Ann" , "John" , "David" , "Serina"],
    "Age" : [21,23,56,23]
}

df = pd.DataFrame(data)
print(df.loc[2])
print(df.loc[2,'Age'])

print(df.iloc[2])
print(df.iloc[2,0])

Name    David
Age        56
Name: 2, dtype: object
56
Name    David
Age        56
Name: 2, dtype: object
David


In [35]:
import pandas as pd;

data = {
    "Calories" : [340,670,450],
    "duration" : [20,40,50]
}

df = pd.DataFrame(data, index = ['day_1' ,'day_2','day_3'])
print(df.loc['day_2'])
print("===========================")
print(df.loc[['day_1' , 'day_3']])
print("===========================")
print(df['Calories'])

Calories    670
duration     40
Name: day_2, dtype: int64
       Calories  duration
day_1       340        20
day_3       450        50
day_1    340
day_2    670
day_3    450
Name: Calories, dtype: int64


In [38]:
import pandas as pd;

data = {
    "Calories" : [340,670,450],
    "duration" : [20,40,50]
}

df = pd.DataFrame(data, index = ['day_1' ,'day_2','day_3'])
print(df.shape)
print(df.size)
print(df.values)
print(type(df.values))

(3, 2)
6
[[340  20]
 [670  40]
 [450  50]]
<class 'numpy.ndarray'>


In [52]:
import pandas as pd;

data = {
    'Age' : [25,30,35,40,60],
    'Salary' : [50000,60000,70000,80000,90000]
}

df = pd.DataFrame(data)

print(df.shape[0])
print(len(df))

5
5


In [51]:
import pandas as pd;

data = {
    'Age' : [25,30,35,40,60],
    'Salary' : [50000,60000,70000,80000,90000]
}

df = pd.DataFrame(data)
print(df.iloc[-1])

Age          60
Salary    90000
Name: 4, dtype: int64


In [67]:
import pandas as pd;

data = {
    'Age' : [25,30,35,40,60],
    'Salary' : [50000,60000,70000,80000,90000],
    'Distance' : [10,20,30,40,44]
}

df = pd.DataFrame(data)
print(df.columns)
print(list(df.columns))
df['Distance'] = [20,30,44,56,60]
df.loc[len(df)] = [21, 40000, 25]
print(df)

Index(['Age', 'Salary', 'Distance'], dtype='object')
['Age', 'Salary', 'Distance']
   Age  Salary  Distance
0   25   50000        20
1   30   60000        30
2   35   70000        44
3   40   80000        56
4   60   90000        60
5   21   40000        25


In [69]:
import pandas as pd;

data = {
    'Age' : [25,30,35,40,60],
    'Salary' : [50000,60000,70000,80000,90000],
    'Distance' : [10,20,30,40,44]
}

df = pd.DataFrame(data)
print(df.sum())
print("------------------------")
print(df.mean())
print("------------------------")
print(df.describe())

Age            190
Salary      350000
Distance       144
dtype: int64
------------------------
Age            38.0
Salary      70000.0
Distance       28.8
dtype: float64
------------------------
             Age        Salary   Distance
count   5.000000      5.000000   5.000000
mean   38.000000  70000.000000  28.800000
std    13.509256  15811.388301  14.042792
min    25.000000  50000.000000  10.000000
25%    30.000000  60000.000000  20.000000
50%    35.000000  70000.000000  30.000000
75%    40.000000  80000.000000  40.000000
max    60.000000  90000.000000  44.000000


In [72]:
import pandas as pd;

data = {
    'Age' : [25,30,35,40,60],
    'Salary' : [50000,60000,70000,80000,90000],
    'Distance' : [10,20,30,40,44]
}

df = pd.DataFrame(data)
print(df[(df['Age'] > 28) & (df['Salary'] > 75000)])

   Age  Salary  Distance
3   40   80000        40
4   60   90000        44


In [89]:
import pandas as pd;

df = pd.DataFrame({
    "Product" : ["Laptop" , "Mouse" , "Keyboard" , "Monitor" , "Headset"],
    "UnitsSold" : [12,50,34,20,40],
    "Price" : [120000,1500,3500,25000,6000],
    "Discount" : [0.10,0.05,0.08,0.12,0.07]
})

df['FinalPrice'] = df['Price'] * (1 - df['Discount'])

df['TotalRevenue'] = df['UnitsSold'] * df["FinalPrice"]
print(df)

print("------------------------------------------------------------------------")

result = df[df["TotalRevenue"] > 500000]
print(result)

print("-------------------------------------------------------------------------")

all_total_revenue = df["TotalRevenue"].sum()
print(all_total_revenue)

    Product  UnitsSold   Price  Discount  FinalPrice  TotalRevenue
0    Laptop         12  120000      0.10    108000.0     1296000.0
1     Mouse         50    1500      0.05      1425.0       71250.0
2  Keyboard         34    3500      0.08      3220.0      109480.0
3   Monitor         20   25000      0.12     22000.0      440000.0
4   Headset         40    6000      0.07      5580.0      223200.0
------------------------------------------------------------------------
  Product  UnitsSold   Price  Discount  FinalPrice  TotalRevenue
0  Laptop         12  120000       0.1    108000.0     1296000.0
-------------------------------------------------------------------------
2139930.0


In [95]:
df = pd.DataFrame({
    "Product" : ["Laptop" , "Mouse" , "Keyboard" , "Monitor" , "Headset"],
    "UnitsSold" : [12,50,34,20,40],
    "Price" : [120000,1500,3500,25000,6000],
    "Discount" : [0.10,0.05,0.08,0.12,0.07]
})

new_df = df.drop('Discount', axis=1)
print(new_df)

print("-------------------------------------------------------------------------")

new_df = df.drop(3 , axis=0)
print(new_df)

    Product  UnitsSold   Price
0    Laptop         12  120000
1     Mouse         50    1500
2  Keyboard         34    3500
3   Monitor         20   25000
4   Headset         40    6000
-------------------------------------------------------------------------
    Product  UnitsSold   Price  Discount
0    Laptop         12  120000      0.10
1     Mouse         50    1500      0.05
2  Keyboard         34    3500      0.08
4   Headset         40    6000      0.07


In [96]:
import pandas as pd;

df = pd.read_csv('person_data.csv')
print(df)

   Name  Age    Country      City
0  Alex   16  Sri Lanka   Colombo
1   Mia   17  Australia    Sydney
2  Ravi   15        USA  New York
3  Sara   16         UK    London
4  Liam   17     Canada   Toronto
